version: '3'
services:
  django:
    build: './docker/build/django'
    ports:
      - 8000:8000
    env_file:
      - './docker/build/django/django.env'
    volumes:
      - ./app:/app
  postgres:
    image: 'postgres:14'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=tasha'
      - 'POSTGRES_PASSWORD=93ptoeuh2893ptoeuh28'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 5000:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=tash@artoftash.com'
      - 'PGADMIN_DEFAULT_PASSWORD=local_password'
    volumes:
      - pga_lib:/var/lib/pgadmin

volumes:
  postgres_data:
  pga_lib: