version: '3'
services:
  django:
    build: './docker/build/django'
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 8081:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=tash@artoftash.com'
      - 'PGADMIN_DEFAULT_PASSWORD=local_password'

volumes:
  postgres_data: